# Generated by Django 5.0.6 on 2024-06-23 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0004_subjectregister_uploadstring_register_subject_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadstring',
            name='register_subject_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datamanagement.subjectregister'),
        ),
    ]
