# Generated by Django 5.0.6 on 2024-06-23 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0002_generatequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='docs/')),
                ('type', models.CharField(choices=[('pdf', 'pdf')], default='pdf', max_length=100)),
                ('row_created', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadString',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('string_prompt', models.CharField(max_length=1000)),
                ('row_created', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='GenerateQuestion',
        ),
    ]
