# Generated by Django 5.0.6 on 2024-06-23 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0003_uploaddocuments_uploadstring_delete_generatequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('row_created', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='uploadstring',
            name='register_subject_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datamanagement.subjectregister'),
        ),
    ]
