# Generated by Django 5.0.6 on 2024-06-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0006_alter_uploadstring_register_subject_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadstring',
            old_name='register_subject_fk',
            new_name='register_subjects',
        ),
        migrations.RemoveField(
            model_name='uploadstring',
            name='subject',
        ),
    ]
