# Generated by Django 5.0.6 on 2024-07-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0007_rename_register_subject_fk_uploadstring_register_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadstring',
            old_name='register_subjects',
            new_name='subjects',
        ),
        migrations.AddField(
            model_name='subjectregister',
            name='index_location',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uploadstring',
            name='isIndexed',
            field=models.BooleanField(default=False),
        ),
    ]
